services:
  api:
    image: thdeathzz/kanjigami:api-latest
    restart: unless-stopped
    tty: true
    ports:
      - 3500:3500
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    environment:
      - NODE_ENV=${NODE_ENV}
      - WEB_URL=${WEB_URL}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URI=${REDIS_URI}
      - MAILER_EMAIL=${MAILER_EMAIL}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - ACCESS_TOKEN_EXPIRES=${ACCESS_TOKEN_EXPIRES}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRES=${REFRESH_TOKEN_EXPIRES}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - VERIFY_TOKEN_SECRET=${VERIFY_TOKEN_SECRET}
      - VERIFY_TOKEN_EXPIRES=${VERIFY_TOKEN_EXPIRES}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_STORAGE_BUCKET=${GOOGLE_STORAGE_BUCKET}
      - GOOGLE_SERVICE_ACCOUNT_PATH=${GOOGLE_SERVICE_ACCOUNT_PATH}
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}

  web:
    image: thdeathzz/kanjigami:web-latest
    restart: unless-stopped
    tty: true
    ports:
      - 3000:3000
    links:
      - api
    depends_on:
      - api

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - ./.data/redis:/data
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-redis}
    ports:
      - ${REDIS_PORT:-6379}:6379

  postgres:
    image: postgres:11-alpine
    restart: unless-stopped
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
